import demo1 from '@/script/1_Boolean';
import demo2 from '@/script/2_Number';
import demo3 from '@/script/3_String';
import demo4 from '@/script/4_Any';
import demo5 from '@/script/5_Void';
import demo6 from '@/script/6_Undefined';
import demo7 from '@/script/7_Null';
import demo8 from '@/script/8_Never';
import demo9 from '@/script/9_Array';
import demo10 from '@/script/10_Tuple';
import demo11 from '@/script/11_Enum';
import demo12 from '@/script/12_Object';
import demo13 from '@/script/13_Interface';
import demo14 from '@/script/14_Class';
import demo15 from '@/script/15_AdvancedType';
import demo16 from '@/script/16_Generic';
import { default as demo17, Validation } from '@/script/17_Namespace';
import demo18 from '@/script/18_Decorator';

console.log('demo17 Validation', Validation);

demo1();
demo2();
demo3();
demo4();
demo5();
demo6();
demo7();
demo8();
demo9();
demo10();
demo11();
demo12();
demo13();
demo14();
demo15();
demo16();
demo17();
demo18();
